server:
  port: 18085
spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: mall-docker-cluster
      cluster-nodes: 172.16.26.128:9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
# #超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

