server:
  port: 18085
spring:
  application:
    name: search
  elasticsearch:
    rest:
      uris: http://172.16.26.128:9200
  #  旧的ElasticSearch配置，不过还是建议在Java类中配置，以方便后面扩展和调试
  #  data:
  #    elasticsearch:
  #      cluster-name: mall-docker-cluster
  #      cluster-nodes: http://172.16.26.128:9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

#超时配置
ribbon:
  ReadTimeout: 300000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

